### ISSUE TITLE
Static quantized model deployment

### ISSUE THREAD

**Issue by amoghatr** [scart97/thunder-speech#69]
Hi! this is an awesome library. I'm using this to deploy a citrinet model on android. I quantized my model and now i have to insert the QuantStub and DeQuantStub to get the output correctly. Can you guide me on how to do it?

**Comment by scart97** [comment]
I usually just torchscript this model and it's fast enough even on android, never tried to quantize it. Can you share the code used to quantize the model and the related error that happened?

**Comment by amoghatr** [comment]
The model is fast, but I'm trying to reduce the size of my model. post training static quantization reduces my 150mb model to around 40mb. But there's an error during inference. the changes i made are : 
1. Added self.quant=torch.quantization.QuantStub() and self.dequant=torch.quantization.DeQuantStub() in the __init__ of BaseCTCModule

2. defined the forward function as : 
```
def forward(self, x: Tensor, lengths: Tensor) -> Tuple[Tensor, Optional[Tensor]]:
        """Process the audio tensor to create the predictions.
        Args:
            x: Audio tensor of shape [batch_size, time]
            lengths: corresponding length of each element in the input tensor.
        Returns:
            Tensor with the predictions.
        """
        x=self.quant(x)
        lengths=lengths.float()
        lengths=self.quant(lengths)
        features, feature_lengths = self.audio_transform(x, lengths)
        encoded, out_lengths = self.encoder(features, feature_lengths)
        return self.dequant(self.decoder(encoded)), self.dequant(out_lengths)
```
3. quantized it using : 

```
backend = "qnnpack"
model.qconfig = torch.quantization.get_default_qconfig(backend)
torch.backends.quantized.engine = backend
model_static_quantized = torch.quantization.prepare(model, inplace=False)
model_static_quantized = torch.quantization.convert(model_static_quantized, inplace=False)
```
4. and then converted it to torchscript using the to_torchscript function

the error i'm getting is : 
```

---> 11 transcriptions = model.predict(audio)
     12 print(transcriptions)

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 56, in predict
    _4 = torch.mul((torch.size(x))[0], [(torch.size(x))[-1]])
    audio_lengths = torch.tensor(_4, dtype=None, device=ops.prim.device(x))
    pred, _5, = (self).forward(x, audio_lengths, )
                 ~~~~~~~~~~~~~ <--- HERE
    text_transform = self.text_transform
    _6 = (text_transform).decode_prediction(torch.argmax(pred, 1), True, )
  File "code/__torch__.py", line 41, in forward
    lengths1 = (quant0).forward(lengths0, )
    audio_transform = self.audio_transform
    _0 = (audio_transform).forward(x0, lengths1, )
          ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    features, feature_lengths, = _0
    encoder = self.encoder
  File "code/__torch__/thunder/blocks/___torch_mangle_75.py", line 17, in forward
    _2 = getattr(self, "2")
    _3 = getattr(self, "3")
    _4 = (_0).forward(audio, audio_lengths, )
          ~~~~~~~~~~~ <--- HERE
    audio0, audio_lengths0, = _4
    _5 = (_1).forward(audio0, audio_lengths0, )
  File "code/__torch__/thunder/blocks/___torch_mangle_72.py", line 11, in forward
    audio_lengths: Tensor) -> Tuple[Tensor, Tensor]:
    layer = self.layer
    _0 = ((layer).forward(audio, ), audio_lengths)
           ~~~~~~~~~~~~~~ <--- HERE
    return _0
  File "code/__torch__/torch/nn/modules/container/___torch_mangle_71.py", line 13, in forward
    _1 = getattr(self, "1")
    input0 = (_0).forward(input, )
    return (_1).forward(input0, )
            ~~~~~~~~~~~ <--- HERE
  def __len__(self: __torch__.torch.nn.modules.container.___torch_mangle_71.Sequential) -> int:
    return 2
  File "code/__torch__/thunder/quartznet/transform.py", line 29, in forward
    preemph = self.preemph
    _4 = torch.slice(torch.slice(x), 1, None, -1)
    _5 = torch.sub(_3, torch.mul(_4, preemph))
                       ~~~~~~~~~ <--- HERE
    return torch.cat([_2, _5], 1)
class PowerSpectrum(Module):

Traceback of TorchScript, original code (most recent call last):
  File "/tmp/ipykernel_5696/390047189.py", line 102, in predict
        #x=self.quant(x)
        audio_lengths = torch.tensor(x.shape[0] * [x.shape[-1]], device=x.device)
        pred, _ = self(x, audio_lengths)
                  ~~~~ <--- HERE
        #pred = self.dequant(pred)
        return self.text_transform.decode_prediction(pred.argmax(1))
  File "/tmp/ipykernel_5696/390047189.py", line 88, in forward
        lengths=lengths.float()
        lengths=self.quant(lengths)
        features, feature_lengths = self.audio_transform(x, lengths)
                                    ~~~~~~~~~~~~~~~~~~~~ <--- HERE
        encoded, out_lengths = self.encoder(features, feature_lengths)
        return self.dequant(self.decoder(encoded)), self.dequant(out_lengths)
  File "/opt/conda/lib/python3.8/site-packages/thunder/blocks.py", line 101, in forward
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        for module in self.children():
            audio, audio_lengths = module(audio, audio_lengths)
                                   ~~~~~~ <--- HERE
        return audio, audio_lengths
  File "/opt/conda/lib/python3.8/site-packages/thunder/blocks.py", line 115, in forward
        self, audio: torch.Tensor, audio_lengths: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.layer(audio), audio_lengths
               ~~~~~~~~~~ <--- HERE
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    def forward(self, input):
        for module in self:
            input = module(input)
                    ~~~~~~ <--- HERE
        return input
  File "<string>", line 3, in forward

def mul(a : float, b : Tensor) -> Tensor:
  return b * a
         ~~~~~ <--- HERE
def add(a : float, b : Tensor) -> Tensor:
  return b + a
RuntimeError: promoteTypes with quantized numbers is not handled yet; figure out what the correct rules should be, offending types: QUInt8 Float
```

It'd be great if you can help me out! thanks!

**Comment by scart97** [comment]
Thanks for the detailed answer! Right now I'm busy with work, meaning that I will only have time to look into detail at this over the weekend.

From a quick glance, the error is happening because the input is quantized (QUInt8 type), while part of the preprocessing tries to multiply it by a float number (the `self.preemph` value). The `audio_transform` part of the model is just basic feature extraction, it's probably better to apply the quantization to the `features` and leave the input value without modifications.

Also, I'm not sure if the lengths need to be quantized.

**Comment by scart97** [comment]
The documentation around quantization is a bit sparse, but I managed to get it working. The masked part of the convolution is not supported, but we can skip this step while exporting the model with the `use_mask` parameter. Regarding the batch normalization layers, you're supposed to fuse it with convolution layers before the quantization happens (https://pytorch.org/tutorials/recipes/fuse.html). Due to the way this model works, this would require a big refactoring of the code. The alternative is to use the QuantStub and DeQuantStub wrapping every batch norm operation. The other change was to use FloatFunctional (https://pytorch.org/docs/stable/generated/torch.nn.quantized.FloatFunctional.html) every time it was necessary to add or multiply two quantized numbers.

Code is uploaded to a specific branch, and will not be merged to master because it's a very disruptive change. You need to install it by running `!pip install git+https://github.com/scart97/thunder-speech.git@quantization_experiment`. Don't install it in the same environment that you already have installed thunder, to avoid conflicts.

The example of exporting citrinet with this branch is present here:
https://gist.github.com/scart97/813424c3fde6242f028262db4ea96ae6

Using the smaller model, the model size was reduced from 40mb to 13mb after quantization. I highly recommend that you evaluate the model performance after quantization, to check how it's working.

**Comment by amoghatr** [comment]
Thanks a ton! this works perfectly!
